# Generated by Django 2.1.7 on 2019-04-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporate',
            name='img',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='img',
        ),
        migrations.AddField(
            model_name='individual',
            name='phone_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporate',
            name='CIN',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
