# Generated by Django 2.1.7 on 2019-04-11 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190411_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporate',
            name='Net_worth',
        ),
    ]
