# Generated by Django 2.1.7 on 2019-04-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_corporate_net_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate',
            name='Net_worth',
            field=models.CharField(default='No', max_length=5),
            preserve_default=False,
        ),
    ]
