# Generated by Django 2.1.7 on 2019-04-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
