# Generated by Django 2.1.7 on 2019-04-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_delete_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_contrib',
            old_name='company_name',
            new_name='category',
        ),
        migrations.AddField(
            model_name='event_contrib',
            name='description',
            field=models.CharField(default='enter Information', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_contrib',
            name='membercount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event_contrib',
            name='textfield',
            field=models.CharField(default='dnscjnkj', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='event_contrib',
            unique_together={('user', 'event_id')},
        ),
    ]
