# Generated by Django 2.1.7 on 2019-04-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20190421_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_creation',
            name='my_budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_creation',
            name='total_budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_contrib',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='event_contrib',
            name='textfield',
            field=models.CharField(default='', max_length=50),
        ),
    ]
