# Generated by Django 2.1.7 on 2019-04-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='date',
        ),
    ]
