# Generated by Django 2.1.7 on 2019-04-21 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_demo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
